### ISSUE TITLE
Examples with separate peers

### ISSUE THREAD

**Issue by papoteur-mga** [robertsdotpm/p2pd#3]
I found `test_tcp_punch.py` and a way to have it working  as standalone.
But I found nowhere a way to have 2 peers on distinct application or machine to do the same. And I didn't find in this example what belongs to peer A and what belongs to peer B.
What I am interested for is hole punching.

**Comment by robertsdotpm** [comment]
Check out test_p2p_pipe. A p2p pipe is like returning a pipe using 4 different methods, punching being one such method. You can specify the method to use:

            pipe, _ = await node_a.connect(
                P2PD_NET_ADDR_BYTES,
                strategies=[P2P_PUNCH]
            )
            
 So you can see here that the test node (node_a) calls connect to a peer's address using P2P_PUCH (TCP punch) as a strategy. The address listed here is a hard-coded constant for a test node running on test.p2pd.net that implements basic methods the node protocol for testing the software.

If you wanted to use the software like you suggested you will have to:

1. Start the node on both computers (a src node, a dest node).
2. Get the destination node's address by calling node.address().
3. Connect to it from the source node by calling await src_node.connect(dest_node.address(), strategies=[P2P_PUNCH])

Some types of NATs don't allow for TCP hole punching to work. For example, symmetric NATs, or NATs that are totally blocked or filtered. A large portion of NAT types are compatible though. Let me know how it goes. Or if you just want to try out punching you can always try to punch to the test node by running this command:

python3 -m unittest test_p2p_pipe.TestP2PPipe.test_remote_punch

This will only run the remote TCP punching test with the test node. The test will probably output information on your interfaces and NAT setup.

**Comment by robertsdotpm** [comment]
@papoteur-mga I think I know what you mean now. I need to make the addressing system easier to use and do as you suggested: create an example that shows how to make a connection from two separate peers. Good ideas.

**Comment by papoteur-mga** [comment]
You're welcome :)

**Comment by robertsdotpm** [comment]
Hello @papoteur-mga, I've built a simple system that provides something like a DNS service for peers that use P2PD. The service is based on a wrapper on top of a signed key-value store using SQLite and PHP. It's experimental for now and usage may end up timing out. I'm in the process of writing a more reliable client so that the script can be hosted on any web host. The example you asked about is now here: https://p2pd.readthedocs.io/en/latest/python/index.html

There's also a small post about how this new 'naming' service works here: https://p2pd.readthedocs.io/en/latest/how.html#naming

My next efforts will be to use P2PD to write a client for 'toxiproxy' which is a neat TCP proxy written in Go that can be used to simulate adverse network conditions. Writing it with P2PD will make it async, multi-interface, and IPv6 ready. But most importantly -- it will teach me how to use the software so I can do more realistic testing for P2PD. I think its an ingenious approach to testing code like this. I may have to write my own replacement server for toxiproxy eventually as theirs doesn't support TCP. But their design seems well thought out.

If you decide to play around with P2PD let me know if you have any more suggestions.

**Comment by robertsdotpm** [comment]
Closing now.
